### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by ymkthr** [ymkthr/chat-space#12]
# IPアドレス
http://18.180.43.87/

**Comment by yasunamiura** [comment]
山内さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**①自動更新ができるようにしましょう**
<img width="1339" alt="ChatSpace_と_ChatSpace_と_ChatSpace" src="https://user-images.githubusercontent.com/52514431/76580937-fa38d000-6514-11ea-8f4e-cfe5171c0cb2.png">

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by ymkthr** [comment]
レビューありがとうございます。
ご指摘いただいた箇所を修正しましたのでご確認ください。

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by ymkthr** [comment]
ありがとうございます！
